runtime: python39

handlers:
 - url: /contract.json
   static_files: static/contract.json
   mime_type: application/json
   upload: contract.json
 - url: /.*
   script: auto

env_variables:
  WEB3_PROVIDER_URI: https://rinkeby.infura.io/v3/6f00acf9331b46c482e81341d0e81e99
