runtime: python39

handlers:
 - url: /contract.json
   static_files: static/contract.json
   mime_type: application/json
 - url: /.*
   script: auto

env_variables:
  WEB3_PROVIDER_URI: http://localhost:8545/
